### ISSUE TITLE
userMsg 存在安全隐患

### ISSUE THREAD

**Issue by lxlneo** [wangweianger/zanePerfor#20]
pass_word 之类的敏感信息不应该存在localStorage 里面

**Comment by wangweianger** [comment]
@lxlneo  pass_word做了加密和

**Comment by wangweianger** [comment]
@lxlneo 
首先谢谢你的提醒。
pass_word做了加密和加盐的处理，即使暴露问题也不大
其次：我这边已经去掉了pass_word的返回，thinks
