### ISSUE TITLE
ip、pv和uv都是0

### ISSUE THREAD

**Issue by juan-imares** [wangweianger/zanePerfor#22]
mongo的webpvuvips表里有数据，但是每条数据的ip和pv、uv都是0，这是为什么呢？另外web_enviroment、web_pages里都没有数据是为什么呢？
<img width="926" alt="WeChat40eed8848bf06a72b6f8d574041b5c8b" src="https://user-images.githubusercontent.com/15643295/57837712-ea1d6a80-77f5-11e9-8105-d0456cb57d1d.png">

**Comment by juan-imares** [comment]
已解决

**Comment by fyzwjd** [comment]
> 已解决

请问是什么原因呢，碰到了同样的问题
