### ISSUE TITLE
通过NGINX代理出现域名域名来源有误,请检查config的origin配置

### ISSUE THREAD

**Issue by pohoc** [wangweianger/zanePerfor#36]
![image](https://user-images.githubusercontent.com/39932748/67937402-83a3d180-fc08-11e9-8a0d-03e9cd618b49.png)

环境是 Linux云服务器  BT面板
也在config.prod.js配置了config.origin   但还是提示，请问下还需要配置哪里？

**Comment by coleShang** [comment]
我也是这个问题   请问 怎么解决的

**Comment by pohoc** [comment]
未解决

ColeShang <notifications@github.com> 于2019年12月13日周五 上午11:00写道：
