### ISSUE TITLE
文档多页面部署案例那里多了\看着好难受

### ISSUE THREAD

**Issue by wertsafc123** [wangweianger/zanePerfor#47]
![image](https://user-images.githubusercontent.com/40291214/77025771-f0a7e000-69cc-11ea-9c3b-9863909b7f12.png)

**Comment by wangweianger** [comment]
![image](https://user-images.githubusercontent.com/16434497/224212830-571a8e6c-63e2-4236-b716-8ee29ea8a007.png)
