### ISSUE TITLE
npm start 运行外网无法访问

### ISSUE THREAD

**Issue by chaos-zhu** [wangweianger/zanePerfor#53]
# 在腾讯云的轻量部署的Ubuntu，redis、mongo等都使用的docker-compose.

## docker容器如下：
![image](https://user-images.githubusercontent.com/44160914/107140047-85eff200-695a-11eb-8e22-029a64559917.png)

## config.prod.js改动如下：
![image](https://user-images.githubusercontent.com/44160914/107140019-4de8af00-695a-11eb-8372-5ffe34f12c6c.png)

![image](https://user-images.githubusercontent.com/44160914/107140017-43c6b080-695a-11eb-8369-166169b7c510.png)

## config.default.js改动如下：
![image](https://user-images.githubusercontent.com/44160914/107140035-707ac800-695a-11eb-9475-15f44be165c6.png)

## npm start 如下：
![image](https://user-images.githubusercontent.com/44160914/107139952-df0b5600-6959-11eb-8897-7aed2a0ec09c.png)

## 访问: http://xxx.xxx.xxx.xxx:7001 
![image](https://user-images.githubusercontent.com/44160914/107140081-b5066380-695a-11eb-880c-1c3f7ff16218.png)

**Comment by chaos-zhu** [comment]
解决了，对egg-script不熟。。。

**Comment by xiaozengtest01** [comment]
大佬，怎么解决的，我也遇到这样的问题
