### ISSUE TITLE
文档（blog.seosiwei.com）看不了

### ISSUE THREAD

**Issue by ooooevan** [wangweianger/zanePerfor#61]
文档看不了了，还会维护吗
可以直接贴到github

![1632628014(1)](https://user-images.githubusercontent.com/25603236/134792768-8ee7a37b-453c-4c9d-a244-93d00633503f.png)

**Comment by xzwc** [comment]
看不了+1  感觉不维护了  好久没更新了

**Comment by wu529778790** [comment]
看不了+1 感觉不维护了 好久没更新了

**Comment by Yan918** [comment]
+1

**Comment by comeriven** [comment]
+1

**Comment by wangweianger** [comment]
已补充了部分文档
