### ISSUE TITLE
关于预警相关业务

### ISSUE THREAD

**Issue by gozeon** [wangweianger/zanePerfor#7]
建议预警相关业务以`plugin`的模式集成[sentry](https://sentry.io/welcome/)

**Comment by Jerrodly** [comment]
@wangweianger  可参考成型产品 https://www.frontjs.com

**Comment by wangweianger** [comment]
@Jerrodly 看了下 不得不说 这个frontjs 的web端上报sdk做的一般额，上报不全，上报用的timeout实现，不能完全的统计资源和ajax的性能

**Comment by wangweianger** [comment]
@Jerrodly 没有预警功能，界面稍显杂乱  上面的功能这个项目都以覆盖，并且上报信息更全面，它上面有Source Map功能，这个后期会加上，预警还在考虑中，后期想好了再加上。
